### PR TITLE
Fixing JUnit plugin

### PR DESCRIPTION
**Pull request by csciuto**

### CODE REVIEW

**Comment by crimsonknave** [comment]
Is this a change that's associated with a new version, or was this always broken? The pipeline builder has a method to declare different xml for different versions of the plugin and that's what should be used if there's a breaking change with a new plugin version.

**Comment by csciuto** [comment]
Much, much older versions of jenkins_pipeline_builder didn't have an error here and still don't, so I figured it's a regression. It looks like in both the older and newer versions of jenkins_pipeline_builder I'm using, we're on the same version of the plugin (is that tied to the version of Jenkins?), 1.18: https://wiki.jenkins.io/display/JENKINS/JUnit+Plugin

**Comment by crimsonknave** [comment]
Sorry, to be clear, I was talking about versions of the plugin. The pipeline builder is designed to support multiple versions of a given plugin so that people aren't locked into a single version. But, if it was just not working in all versions it doesn't need to be broken out by version.

**Comment by csciuto** [comment]
Yeah, that's what I was trying to say, but I'm also a bit over my head here. It looks to me like this likely broke for all versions of the plugin due to changes to pipeline_builder, but I'm not sure how we'd test that. Do you think we need some sort of regression testing against other plugin versions or does this seem OK?

Thanks for helping with this btw :-)

**Pull request merged**
